export {
    default as env,
    DATABASE_URL,
    JWT_SECRET,
    NODE_ENV,
    PORT,
    REDIS_DB,
    REDIS_HOST,
    REDIS_PORT,
    SMTP_HOST,
    SMTP_PASSWORD,
    SMTP_PORT,
    SMTP_USER,
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN,
    TWILIO_VERIFY_SERVICE_SID,
    TWILIO_WHATSAPP_FROM,
} from "./envVars";

